"""create review_sessions and findings tables

Revision ID: caabe0f6a3a7
Revises: a2f452d3aa86
Create Date: 2026-08-31 19:35:18.227621

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "caabe0f6a3a7"
down_revision: str | Sequence[str] | None = "a2f452d3aa86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
