"""create review_sessions and findings tables

Revision ID: caabe0f6a3a7
Revises: a2f452d3aa86
Create Date: 2026-08-31 19:35:18.227621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caabe0f6a3a7'
down_revision: Union[str, Sequence[str], None] = 'a2f452d3aa86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
